### PR TITLE
Fix doc comments and add missing parameter in getUrlsFromWebsiteId

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by thelfensdrfer** [comment]
Can you check the indentation. It seems of at a few lines, especially the doc block comments. Shouldn't they be indented at the same level as the following method?

**Comment by simonschaufi** [comment]
Sure, they should. I just see the mess. I would like to use PSR standards (use spaces). Can I reformat the whole file?

**Comment by thelfensdrfer** [comment]
Yes you can! Thanks for your PR.

**Comment by simonschaufi** [comment]
Thank you for merging this!

**Pull request merged**
