### PR TITLE
[!!!] Breaking: Add more parameters to SitesManager.addSite

### PR DESCRIPTION
**Pull request by simonschaufi**
Add settingValues and excludeUnknownUrls to addSite and sync them with the official Piwik API.
Beware of new parameter order!

### CODE REVIEW

**Comment by simonschaufi** [comment]
> phpunit/phpunit 6.4.4 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement.

Should I downgrade phpunit again?

**Comment by thelfensdrfer** [comment]
Thanks for your work! You can add `php >= 7` as a requirement in the composer.json file. Should be fine. I will create a new minor release for this pull request anyways.

**Comment by simonschaufi** [comment]
done

**Comment by thelfensdrfer** [comment]
I've used avatarmaker.com or some similar service ;)

**Pull request merged**
